CREATE DATABASE PLAYSPACE_WEB;
USE PLAYSPACE_WEB;

/*USUARIOS*/
/*ID_USUARIO 
ID_DISPOSITIVO 
NOMBRE_USUARIO 
ID_FOTO_PERFIL
CONTRASENA
CORREO
CALIFICACION_USUARIO
CALIFICACION_EVENTOS*/
CREATE TABLE USUARIOS(  
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(45) NOT NULL, 
    ID_FOTO_PERFIL tinyint NOT NULL,
    CONTRASENA VARCHAR(60) NOT NULL, 
    CORREO VARCHAR(60) NOT NULL, 
    PARTICIPACIONES INT,
    INASISTENCIAS INT,
    EVENTOS_REALIZADOS INT,
    FECHA_CAMBIO_NOMBRE DATETIME,
    CLAVE_VERIFICACION VARCHAR(12),
    FECHA_CLAVE_VERIFICACION DATETIME,
    CALIFICACION_USUARIO FLOAT NOT NULL DEFAULT 5.0,
    CALIFICACION_EVENTOS FLOAT,
    FECHA_REPORTE_EVENTO DATETIME,
    PRIMARY KEY(ID_USUARIO));
/*REPORTES*/
/*ID_USUARIO
TIPO_REPORTE
FECHA_REPORTE*/
CREATE TABLE REPORTES(  
	ID_USUARIO INT NOT NULL, 
    TIPO_REPORTE INT NOT NULL, 
    FECHA_REPORTE DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE);
/*EVENTOS*/
/*ID_USUARIO
ID_EVENTO
TAMANO_EVENTO
TIPO_EVENTO
DESCRIPCION
UBICACIONLAT
UBICACIONLON
FECHA_INICIO
FECHA_FIN*/
CREATE TABLE EVENTOS(   
	ID_USUARIO INT NOT NULL,
	ID_EVENTO INT NOT NULL, 
    TAMANO_EVENTO INT,
    TIPO_EVENTO INT NOT NULL, 
    DESCRIPCION TEXT,
    UBICACION_LAT FLOAT NOT NULL,
    UBICACION_LON FLOAT NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    CALIFICACION_EVENTO DOUBLE DEFAULT 5.0,
    CANTIDAD_CALIFICACIONES INT DEFAULT 0,
    EVENTO_FALSO INT DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE, 
    PRIMARY KEY (ID_EVENTO));
/*REPORTANTES_EVENTOS*/
/*ID_EVENTO
ID_REPORTANTE*/
CREATE TABLE REPORTANTES_EVENTO(
	ID_EVENTO INT NOT NULL,
    ID_REPORTANTE INT NOT NULL,
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_REPORTANTE) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE);
/*PARTICIPANTES_EVENTOS*/
/*ID_EVENTO
ID_PARTICIPANTE
MALOS_COMPORTAMIENTOS*/
CREATE TABLE PARTICIPANTES_EVENTO( 
	ID_EVENTO INT NOT NULL,  
	ID_PARTICIPANTE INT NOT NULL, 
    MALOS_COMPORTAMIENTOS INT DEFAULT 0,
    ASISTIO INT,
    CALIFICACION_EVENTO INT,
    FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO) ON DELETE CASCADE ON UPDATE CASCADE);
/*PARTICIPANTES_EXPULSADOS*/
/*ID_EVENTO
ID_EXPULSADO
*/
CREATE TABLE PARTICIPANTES_EXPULSADOS ( 
	ID_EVENTO INT NOT NULL, 
	ID_EXPULSADO INT NOT NULL,
	FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO) ON DELETE CASCADE ON UPDATE CASCADE);
/*CHAT_EVENTO*/
/*ID_EVENTO
MENSAJE
FECHA_MENSAJE
ID_REMITENTE*/
CREATE TABLE CHAT_EVENTO(   
	ID_EVENTO INT NOT NULL, 
	MENSAJE TEXT NOT NULL, 
    FECHA_MENSAJE DATETIME, 
    ID_REMITENTE INT, 
    FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO) ON DELETE CASCADE ON UPDATE CASCADE);
/*AMIGOS*/
/*ID_SOLICITANTE
ID_OBJETIVO
AMISTAD
KEY_ENCRIPTACION_SOLICITANTE
KEY_ENCRIPTACION_OBJETIVO
*/
CREATE TABLE AMIGOS(
	ID_CHAT VARCHAR(45) NOT NULL,
	ID_SOLICITANTE INT NOT NULL, 
	ID_OBJETIVO INT NOT NULL, 
    AMISTAD BOOLEAN, 
    KEY_ENCRIPTACION_SOLICITANTE TEXT, 
    KEY_ENCRIPTACION_OBJETIVO TEXT,
    PRIMARY KEY (ID_CHAT),
    FOREIGN KEY (ID_SOLICITANTE) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_OBJETIVO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE);

/*CHAT_AMIGOS*/
/*ID_CHAT
MENSAJE
FECHA_MENSAJE
ID_REMITENTE*/
CREATE TABLE CHAT_AMIGOS(	
	ID_CHAT VARCHAR(45) NOT NULL,
	MENSAJE TEXT NOT NULL, 
    FECHA_MENSAJE DATETIME, 
    ID_REMITENTE INT, 
    FOREIGN KEY (ID_CHAT) REFERENCES AMIGOS(ID_CHAT) ON DELETE CASCADE ON UPDATE CASCADE);
    
/*TIENDAS*/
/*ID_USUARIO
ID_TIENDA
UBICACIONLAT
UBICACIONLON
DESCRIPCION
TELEFONO
CORREO
*/
CREATE TABLE TIENDAS(   
	ID_USUARIO INT NOT NULL, 
    ID_TIENDA INT NOT NULL,
    NOMBRE_TIENDA TEXT NOT NULL, 
    UBICACION_LAT FLOAT NOT NULL,
    UBICACION_LON FLOAT NOT NULL,
    DESCRIPCION TEXT, 
    TELEFONO BIGINT, 
    CORREO VARCHAR(30),
    DIRECCION TEXT, 
    FIN_PUBLICACION DATETIME, 
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE, 
    PRIMARY KEY (ID_TIENDA));
/*PRODUCTOS*/
/*ID_TIENDA
NOMBRE_PRODUCTO
PRECIO_PRODUCTO
FOTO_PRODUCTO*/
CREATE TABLE PRODUCTOS( 
	ID_TIENDA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    NOMBRE_PRODUCTO TEXT NOT NULL, 
    PRECIO_PRODUCTO DOUBLE NOT NULL,
    FOTO_PRODUCTO TEXT,
    FOREIGN KEY (ID_TIENDA) REFERENCES TIENDAS(ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE);
/*TIPO_PRODUCTOS*/
/*ID_TIENDA
TIPO_PRODUCTOS*/
CREATE TABLE TIPO_PRODUCTOS(
	ID_TIENDA INT NOT NULL,
	FOREIGN KEY (ID_TIENDA) REFERENCES TIENDAS(ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE, 
    TIPO_PRODUCTOS VARCHAR(30));

CREATE TABLE CHAT_TIENDA(   
	ID_TIENDA INT NOT NULL, 
    ID_REMITENTE INT NOT NULL,
	MENSAJE TEXT NOT NULL, 
    FECHA_MENSAJE DATETIME NOT NULL,
    MENSAJE_RESPUESTA TEXT,
    FOREIGN KEY(ID_TIENDA) REFERENCES TIENDAS(ID_TIENDA) ON DELETE CASCADE ON UPDATE CASCADE);
    
CREATE TABLE PAPELERA_DE_RECICLAJE(
	MENSAJE TEXT,
    FECHA_MENSAJE DATETIME DEFAULT NOW());
    
INSERT INTO USUARIOS (ID_USUARIO,
						NOMBRE_USUARIO,
                        ID_FOTO_PERFIL,
                        CONTRASENA,
                        CORREO) VALUES (1,
										'DonHardCore',
										4,
										'elbiernez',
										'flipas@gmail.com');
INSERT INTO USUARIOS (ID_USUARIO,
						NOMBRE_USUARIO,
                        ID_FOTO_PERFIL,
                        CONTRASENA,
                        CORREO) VALUES(2,
										'Elquereparte',
										1,
										'lasostias',
										'sinconsagrar@gmail.com');
INSERT INTO USUARIOS (ID_USUARIO,
						NOMBRE_USUARIO,
                        ID_FOTO_PERFIL,
                        CONTRASENA,
                        CORREO) VALUES(3,
										'TestThis',
										16,
										'Salu2prro',
										'test@gmail.com');
INSERT INTO USUARIOS (ID_USUARIO,
						NOMBRE_USUARIO,
                        ID_FOTO_PERFIL,
                        CONTRASENA,
                        CORREO) VALUES(4,
										'FelizJuevez',
										1,
										'YelCuerpoYa',
										'nilosabe@gmail.com');
INSERT INTO USUARIOS (ID_USUARIO,
						NOMBRE_USUARIO,
                        ID_FOTO_PERFIL,
                        CONTRASENA,
                        CORREO) VALUES(5,
										'DeltaForce',
										20,
										'25CountingStars25',
										'dontforget@gmail.com');
			
INSERT INTO REPORTES VALUES(2,
							4,
                            current_timestamp());                           
INSERT INTO REPORTES VALUES(2,
							1,
                            '2018-08-02 12:33:11');
INSERT INTO REPORTES VALUES(2,
							1,
                            '2021-05-24 12:33:11');
 
INSERT INTO EVENTOS (ID_USUARIO,
					ID_EVENTO,
                    TIPO_EVENTO,
                    UBICACION_LAT,
                    UBICACION_LON,
                    FECHA_INICIO,
                    FECHA_FIN) VALUES (2,21,56,14.68645464,3.9806785,current_timestamp(),current_timestamp());
INSERT INTO EVENTOS (ID_USUARIO,
					ID_EVENTO,
                    TIPO_EVENTO,
                    UBICACION_LAT,
                    UBICACION_LON,
                    FECHA_INICIO,
                    FECHA_FIN) VALUES (1,11,13,4.68645464,-3.9806785,current_timestamp(),current_timestamp());
INSERT INTO EVENTOS (ID_USUARIO,
					ID_EVENTO,
                    TIPO_EVENTO,
                    UBICACION_LAT,
                    UBICACION_LON,
                    FECHA_INICIO,
                    FECHA_FIN) VALUES (2,22,72,6.68645464,0.9806785,current_timestamp(),current_timestamp());

INSERT INTO	PARTICIPANTES_EVENTO (ID_EVENTO,
								  ID_PARTICIPANTE) VALUES (11,1);
INSERT INTO	PARTICIPANTES_EVENTO (ID_EVENTO,
								  ID_PARTICIPANTE) VALUES (11,2);
INSERT INTO	PARTICIPANTES_EVENTO (ID_EVENTO,
								  ID_PARTICIPANTE) VALUES (11,3);
INSERT INTO	PARTICIPANTES_EVENTO (ID_EVENTO,
								  ID_PARTICIPANTE) VALUES (11,4);
INSERT INTO TIENDAS VALUES (1,
							11,
                            'Tienda balones', 
							6.578139480,
                            3.8902312,
                            'Vendemos balones y.... bueno.... solo eso.',
                            3213652541, 
							'test@gmail.com',
                            'cra 24 no 25 - 77',
                            current_timestamp());

INSERT INTO CHAT_TIENDA VALUES (11,
								4,
                                'Aquí venden queso?',
                                current_timestamp(),
                                'Nel kbro');
INSERT INTO CHAT_TIENDA VALUES (11,
								4,
                                'Aquí venden queso?',
                                current_timestamp(),
                                'Que no wey');
INSERT INTO CHAT_TIENDA VALUES (11,
								4,
                                'Aquí venden queso?',
                                 current_timestamp(),
                                'No andei weando kbron');
	
INSERT INTO AMIGOS (ID_CHAT, 
					ID_SOLICITANTE, 
                    ID_OBJETIVO, 
                    AMISTAD, 
                    KEY_ENCRIPTACION_SOLICITANTE, 
                    KEY_ENCRIPTACION_OBJETIVO) VALUES ( '1 2', 
														'1', 
                                                        '2', 
                                                        '1', 
                                                        'c234ecb19d60403aac81bf6b26211b74', 
                                                        '4ca018fafdf74abacc58a54a5fa602d2');
INSERT INTO AMIGOS (ID_CHAT, 
					ID_SOLICITANTE, 
                    ID_OBJETIVO, 
                    AMISTAD, 
                    KEY_ENCRIPTACION_SOLICITANTE, 
                    KEY_ENCRIPTACION_OBJETIVO) VALUES ( '2 5', 
														'2', 
                                                        '5', 
                                                        '1', 
                                                        '95009d5885bb088bea909b62a6b1bd36', 
                                                        'f6d51c6e1eff55854257acbe49b15162');
INSERT INTO AMIGOS (ID_CHAT, 
					ID_SOLICITANTE, 
                    ID_OBJETIVO, 
                    AMISTAD) VALUES (   '1 4', 
										'1', 
										'4', 
										'0');
    
#=====================================================
#SELECT ID_SOLICITANTE FROM AMIGOS WHERE ID_OBJETIVO = '2' AND AMISTAD = '1';
#=====================================================
CREATE VIEW INFO_PARTICIPANTES_EVENTO AS
SELECT  T3.ID_EVENTO, 
		ID_PARTICIPANTE, 
        ID_FOTO_PERFIL, 
        NOMBRE_USUARIO, 
        CASE    WHEN (T3.ID_EVENTO = T2.ID_EVENTO) AND (ID_PARTICIPANTE = T2.ID_USUARIO) 
				THEN 1 
                ELSE 0 
		END AS 'ADMINISTRADOR', 
        CALIFICACION_USUARIO
FROM USUARIOS T1, EVENTOS T2, PARTICIPANTES_EVENTO T3
WHERE T3.ID_PARTICIPANTE = T1.ID_USUARIO
	AND T3.ID_EVENTO = T2.ID_EVENTO
GROUP BY ID_PARTICIPANTE;
    
#SELECT * FROM INFO_PARTICIPANTES_EVENTO;

#DROP VIEW INFO_PARTICIPANTES_EVENTO;

CREATE VIEW INFO_AMIGOS AS
SELECT 	ID_CHAT,
		(case when T1.ID_SOLICITANTE = T2.ID_USUARIO THEN T1.ID_SOLICITANTE ELSE T1.ID_OBJETIVO END) AS ID_USUARIO,
		(case when T1.ID_SOLICITANTE = T2.ID_USUARIO THEN T1.ID_OBJETIVO ELSE T1.ID_SOLICITANTE END) AS ID_AMIGO, 
		(SELECT NOMBRE_USUARIO FROM USUARIOS WHERE ID_USUARIO = (case when T1.ID_SOLICITANTE = T2.ID_USUARIO THEN T1.ID_OBJETIVO ELSE T1.ID_SOLICITANTE END))AS NOMBRE_AMIGO,
		(SELECT ID_FOTO_PERFIL FROM USUARIOS WHERE ID_USUARIO = (case when T1.ID_SOLICITANTE = T2.ID_USUARIO THEN T1.ID_OBJETIVO ELSE T1.ID_SOLICITANTE END)) AS ID_FOTO_PERFIL,
        T1.AMISTAD AS AMISTAD
FROM AMIGOS T1, USUARIOS T2 
WHERE (T2.ID_USUARIO = T1.ID_SOLICITANTE
	OR T2.ID_USUARIO = T1.ID_OBJETIVO);

#DROP VIEW INFO_AMIGOS;
#SELECT * FROM INFO_AMIGOS WHERE ID_USUARIO = 1;

CREATE VIEW LISTA_EVENTOS AS
SELECT T1.ID_EVENTO, T1.TIPO_EVENTO, COUNT(T2.ID_PARTICIPANTE),T1.FECHA_INICIO
FROM EVENTOS T1, PARTICIPANTES_EVENTO T2
WHERE T1.ID_EVENTO = T2.ID_EVENTO
GROUP BY T1.ID_EVENTO
ORDER BY T1.FECHA_INICIO ASC;

#DROP VIEW LISTA_EVENTOS;
#SELECT  * FROM LISTA_EVENTOS;

CREATE VIEW LISTA_TIENDAS AS
SELECT T1.ID_TIENDA, T1.NOMBRE_TIENDA,T1.FIN_PUBLICACION,T2.TIPO_PRODUCTOS
FROM TIENDAS T1, TIPO_PRODUCTOS T2
WHERE T1.ID_TIENDA = T2.ID_TIENDA
ORDER BY T1.FIN_PUBLICACION DESC;

#DROP VIEW LISTA_TIENDAS;
#SELECT * FROM LISTA_TIENDAS;

CREATE VIEW INFO_BASICA_USUARIO AS
SELECT ID_USUARIO,NOMBRE_USUARIO,ID_FOTO_PERFIL
FROM USUARIOS;

#SELECT * FROM INFO_BASICA_USUARIO WHERE ID_USUARIO = '1';
#SELECT * FROM INFO_BASICA_USUARIO;
#=====================================================
#=====================================================
CREATE TRIGGER CREADO_CUENTA
AFTER INSERT 
ON USUARIOS
FOR EACH ROW
INSERT INTO PAPELERA_DE_RECICLAJE (MENSAJE) VALUES ('Cuenta Creada');

CREATE TRIGGER CREADO_TIENDA
AFTER INSERT
ON TIENDAS
FOR EACH ROW
INSERT INTO PAPELERA_DE_RECICLAJE (MENSAJE) VALUES ('Tienda Creada');

CREATE TRIGGER BORRADO_CUENTA
AFTER DELETE 
ON USUARIOS
FOR EACH ROW
INSERT INTO PAPELERA_DE_RECICLAJE (MENSAJE) VALUES ('Cuenta Borrada');

#=====================================================
#=====================================================
